### ISSUE TITLE
Add semantic versioning

### ISSUE THREAD

**Issue by GradedJestRisk** [nennigb/EasterEig#3]
Claimed version (in setup.py) is 1.0.0, whereas the last commit was a bugfix ("Fix problem to load eig object without eigenvector"). This may confuse everyone which use the code. I suggest to use [semantic versioning](https://semver.org/) standard, implemented by [semver python module](https://pypi.org/project/semver/) and bumping version on 1.0.1 on next PR.

**Comment by nennigb** [comment]
Hi,

I understand your remarks and semantic versioning is very appealing. However I still have to explore to find the good solution for this project especially to limit the overhead.

BN
