### ISSUE TITLE
Enable contributing

### ISSUE THREAD

**Issue by GradedJestRisk** [nennigb/EasterEig#4]
Although the documentation is quite extensive about how to use EasterEig, there's nothing such as  contribution guidelines. 

Here's some suggestions:
- create a CONTRIBUTING.md;
- use a source-code analyzer (linter, eg. [Pylama](Pylama)) to make code homogeneous among contributors;
- ensure test code coverage provide enough trust so new features don't introduce regressions.   

**Test coverage**
Test coverage is inteded to check if tests are effectively testing code (execute it, and check assertion). This can only be done using mutation testing, eg.[MutPy](https://pypi.org/project/MutPy/)). Here, testing is done using doctest, and there's no reliable mutation-testing libray using doctest. [This library](https://schinckel.net/tags/mutation-testing/) is intended as a toy for learning.  I've not been able to run [xmutant](https://github.com/vrthra/xmutant.py)). There's a way, thought, by making unittest run doctest.

Simple coverage (has code been executed during test ?) is a fallback mechanism: only low coverage indicate something bad. 100% coverage, without any assertion, doesn't prevent anything bad from happening, even crashes.
 
[Coverage](https://coverage.readthedocs.io) can handle doctest, and gave a 60% coverage

![image](https://user-images.githubusercontent.com/37769607/78503397-98ac0000-7766-11ea-8408-946912c68552.png)

To run:
- pip3 install coverage
- coverage run --source=. -m eastereig
- coverage report -m

**Comment by nennigb** [comment]
Hi,

I will add a CONTRIBUTING.md soon.
Concerning the coverage, I will add that soon though github action.

BN
